from PyQt5 import QtCore, QtGui, QtWidgets 
from functools import partial
from domain.square import Square

class Ui_Dialog(object):
    def setupUi(self, Dialog, game):
        # Make some variables
        self._game = game
        self._Dialog = Dialog
        self.playerMove = False

        Dialog.setObjectName("Dialog")
        Dialog.resize(922, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(30, 50, 610, 10))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(50, 30, 10, 610))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(730, 230, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(730, 270, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(690, 180, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(720, 340, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.startGame)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(90, 30, 10, 610))
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(130, 30, 10, 610))
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(170, 30, 10, 610))
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(210, 30, 10, 610))
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(250, 30, 10, 610))
        self.line_7.setLineWidth(3)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setGeometry(QtCore.QRect(290, 30, 10, 610))
        self.line_8.setLineWidth(3)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Dialog)
        self.line_9.setGeometry(QtCore.QRect(330, 30, 10, 610))
        self.line_9.setLineWidth(3)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Dialog)
        self.line_10.setGeometry(QtCore.QRect(370, 30, 10, 610))
        self.line_10.setLineWidth(3)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Dialog)
        self.line_11.setGeometry(QtCore.QRect(410, 30, 10, 610))
        self.line_11.setLineWidth(3)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(Dialog)
        self.line_12.setGeometry(QtCore.QRect(450, 30, 10, 610))
        self.line_12.setLineWidth(3)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(Dialog)
        self.line_13.setGeometry(QtCore.QRect(490, 30, 10, 610))
        self.line_13.setLineWidth(3)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(Dialog)
        self.line_14.setGeometry(QtCore.QRect(530, 30, 10, 610))
        self.line_14.setLineWidth(3)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(Dialog)
        self.line_15.setGeometry(QtCore.QRect(570, 30, 10, 610))
        self.line_15.setLineWidth(3)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(Dialog)
        self.line_16.setGeometry(QtCore.QRect(610, 30, 10, 610))
        self.line_16.setLineWidth(3)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(Dialog)
        self.line_17.setGeometry(QtCore.QRect(30, 90, 610, 10))
        self.line_17.setLineWidth(3)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(Dialog)
        self.line_18.setGeometry(QtCore.QRect(30, 130, 610, 10))
        self.line_18.setLineWidth(3)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(Dialog)
        self.line_19.setGeometry(QtCore.QRect(30, 170, 610, 10))
        self.line_19.setLineWidth(3)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(Dialog)
        self.line_20.setGeometry(QtCore.QRect(30, 210, 610, 10))
        self.line_20.setLineWidth(3)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(Dialog)
        self.line_21.setGeometry(QtCore.QRect(30, 250, 610, 10))
        self.line_21.setLineWidth(3)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(Dialog)
        self.line_22.setGeometry(QtCore.QRect(30, 290, 610, 10))
        self.line_22.setLineWidth(3)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(Dialog)
        self.line_23.setGeometry(QtCore.QRect(30, 330, 610, 10))
        self.line_23.setLineWidth(3)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(Dialog)
        self.line_24.setGeometry(QtCore.QRect(30, 370, 610, 10))
        self.line_24.setLineWidth(3)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_25 = QtWidgets.QFrame(Dialog)
        self.line_25.setGeometry(QtCore.QRect(30, 410, 610, 10))
        self.line_25.setLineWidth(3)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_26 = QtWidgets.QFrame(Dialog)
        self.line_26.setGeometry(QtCore.QRect(30, 450, 610, 10))
        self.line_26.setLineWidth(3)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(Dialog)
        self.line_27.setGeometry(QtCore.QRect(30, 490, 610, 10))
        self.line_27.setLineWidth(3)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(Dialog)
        self.line_28.setGeometry(QtCore.QRect(30, 530, 610, 10))
        self.line_28.setLineWidth(3)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(Dialog)
        self.line_29.setGeometry(QtCore.QRect(30, 570, 610, 10))
        self.line_29.setLineWidth(3)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(Dialog)
        self.line_30.setGeometry(QtCore.QRect(30, 610, 610, 10))
        self.line_30.setLineWidth(3)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(660, 410, 211, 71))
        self.label_2.setObjectName("label_2")
        self.line_2.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.line_17.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_20.raise_()
        self.line_21.raise_()
        self.line_22.raise_()
        self.line_23.raise_()
        self.line_24.raise_()
        self.line_25.raise_()
        self.line_26.raise_()
        self.line_27.raise_()
        self.line_28.raise_()
        self.line_29.raise_()
        self.line_30.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.label_3 = QtWidgets.QLabel(self._Dialog)
        self.label_3.setGeometry(QtCore.QRect(690, 510, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def startGame(self):
        diff = 1
        if self.radioButton.isChecked():
            diff = 1
        elif self.radioButton_2.isChecked():
            diff = 2
        self._game.setDifficulty(diff)
        self.playerMove = True
        
    def createButtons(self):
        self.pushButtons = []
        for i in range(225):
            x = 40 * (1 + i % 15)
            y = 40 * (1 + i // 15)
            self.pushButtons.append(QtWidgets.QPushButton(self._Dialog))
            self.pushButtons[i].setGeometry(QtCore.QRect(x, y, 30, 30))
            self.pushButtons[i].setStyleSheet("background-color: rgb(160, 160, 160);")
            self.pushButtons[i].setText("")
            self.pushButtons[i].setObjectName("pushButton_" + str(i))
            self.pushButtons[i].raise_()
            self.pushButtons[i].clicked.connect(partial(self.onClick, i))

    def computerMove(self):
        if not self.playerMove:
            aux = self._game.moveComputer('O', 'X')
            self.setButtonWhite(aux.row * 15 + aux.col)
            if self._game.board.isWon():
                self.gameWon()
                return
            self.playerMove = True

    def onClick(self, idx):
        if self.playerMove and not self._game.board.isWon() and self._game.board.getValAtPos(Square(idx//15, idx%15)) == 0:
            self.pushButtons[idx].setStyleSheet("background-color: rgb(0, 0, 0);")
            self._game.moveHuman(Square(idx//15, idx%15), 'X')
            if self._game.board.isWon():
                self.gameWon()
                return
            self.playerMove = False
            self.computerMove()

    def startOnClick(self):
        self.startGame()

    def setButtonWhite(self, idx):
        self.pushButtons[idx].setStyleSheet("background-color: rgb(255, 255, 255);")

    def gameWon(self):

        string = ""
        if self.playerMove == False:
            string = "Computer wins!"
        else:
            string = "Player wins!"

        _translate = QtCore.QCoreApplication.translate
        self.label_3.setText(_translate("Dialog", string))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton.setText(_translate("Dialog", "Easy"))
        self.radioButton_2.setText(_translate("Dialog", "Hard"))
        self.label.setText(_translate("Dialog", "Choose Difficulty:"))
        self.pushButton.setText(_translate("Dialog", "Start"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">After start, click on the board</p><p align=\"center\">buttons to place a game piece</p></body></html>"))
